-- Persistent storage for the real-estate monitor.
-- Run this once in Supabase SQL Editor before enabling Cloud storage.

create table if not exists public.alert_rules (
    id bigint generated by default as identity primary key,
    region text not null,
    lawd_cd text,
    max_price_100m double precision not null,
    min_area double precision not null,
    event_type text not null,
    supply_type text default '전체',
    property_type text default '아파트',
    enabled boolean default true,
    created_at text not null
);

create table if not exists public.notifications (
    id bigint generated by default as identity primary key,
    event_key text unique,
    category text not null,
    title text not null,
    message text not null,
    is_read boolean default false,
    created_at text not null
);

create table if not exists public.source_snapshots (
    source text not null,
    item_key text not null,
    payload jsonb not null,
    first_seen_at text not null,
    last_seen_at text not null,
    primary key (source, item_key)
);

create table if not exists public.app_settings (
    key text primary key,
    value text not null
);

-- Data API requests use the service-role key stored only in Streamlit Cloud
-- and GitHub Actions. No anonymous or authenticated client can read tables.
alter table public.alert_rules enable row level security;
alter table public.notifications enable row level security;
alter table public.source_snapshots enable row level security;
alter table public.app_settings enable row level security;
