"""Generate services/development_geocode_targets.py from the canonical file.

The geocode target set is: already in the database AND carrying an address (128 of the
canonical 183). It lives in services/ because the deploy uploads api/, services/ and
web/ to the Space but not data/, and the NAVER credential exists only on the Space.
Publishing the whole data/development directory to the Space would also put the
internal duplicate-review and quarantine files there, which is not wanted.

Run with --write after the canonical file changes; tests fail if the two drift apart.
"""
import argparse
import json
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / 'data/development'
OUTPUT = ROOT / 'services/development_geocode_targets.py'
HEADER = '''"""The canonical projects that can be geocoded: in the database and carrying an address.

Generated by scripts/build_zipon_geocode_targets.py from
data/development/pilot_canonical_verified_20260927.json. Do not hand-edit; a test
asserts this table still matches the canonical file exactly.

Why a generated table in services/ rather than reading the canonical file: the deploy
uploads api/, services/ and web/ to the Space but deliberately not data/, and the NAVER
credential exists only on the Space. Keeping the target list here is what lets the bulk
geocode run where the credential is, without publishing the internal review files.

Scope, so the numbers are never confused with each other:
  183  raw source candidate records == 183 canonical projects (1:1, no merge)
  149  canonical projects carrying an address
   34  canonical projects with no address at all, every one of them 신속통합기획
  130  canonical projects already in the database
  128  in the database AND carrying an address  <- this table
    2  in the database with no address (both 신속통합기획)
   21  carrying an address but still quarantined, so not writable yet
"""

COLUMNS = ('project_id', 'project_name', 'canonical_address', 'district', 'dong',
           'project_type', 'program')
ROWS = (
'''
FOOTER = ''')


def targets():
    """Rows as dicts, in a stable district then project_id order."""
    return [dict(zip(COLUMNS, row)) for row in ROWS]
'''


def load(name):
    return json.loads((DATA / name).read_text(encoding='utf-8'))


def in_database():
    ids = {p['project_id'] for p in load('db_baseline_20260927.json')['projects']}
    return ids | {i for b in load('bulk_import_result_20260927.json')['batches']
                  for i in b['project_ids']}


def rows():
    """In the database and carrying an address, ordered by district then project_id."""
    ids = in_database()
    out = []
    for project in load('pilot_canonical_verified_20260927.json')['projects']:
        project_id = project['raw']['candidate_ids'][0]
        location, classification = project['location'], project['classification']
        if project_id not in ids or not location['representative_address']:
            continue
        out.append((project_id, project['identity']['official_project_name'],
                    location['representative_address'], location['district'],
                    location['dong'], classification['canonical_project_type'],
                    classification['program']))
    return sorted(out, key=lambda row: (row[3], row[0]))


def render(table):
    body = []
    for row in table:
        program = 'None' if row[6] is None else "'%s'" % row[6]
        body.append("    ('%s',\n     '%s',\n     '%s',\n     '%s', '%s', '%s', %s),"
                    % (row[0], row[1], row[2], row[3], row[4], row[5], program))
    return HEADER + '\n'.join(body) + FOOTER


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument('--write', action='store_true', help='write the generated module')
    args = ap.parse_args()
    table = rows()
    text = render(table)
    if args.write:
        OUTPUT.write_text(text, encoding='utf-8')
    current = OUTPUT.read_text(encoding='utf-8') if OUTPUT.exists() else ''
    print(json.dumps({'targets': len(table), 'written': bool(args.write),
                      'up_to_date': current == text,
                      'file': str(OUTPUT.relative_to(ROOT))}, ensure_ascii=False))
    return 0


if __name__ == '__main__':
    sys.exit(main())
