-- REVIEW ONLY: new zipon-realestate database. Do not run on the old production database.
-- No seed data; no connection/Secret changes. Execute as Dashboard postgres after review.
-- Existing four table definitions are copied verbatim from supabase/schema.sql.
BEGIN;
SET LOCAL lock_timeout = '5s';
SET LOCAL statement_timeout = '60s';
SET LOCAL search_path = pg_catalog, public, extensions;

DO $guard$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_catalog.pg_extension e
                 JOIN pg_catalog.pg_namespace n ON n.oid=e.extnamespace
                 WHERE e.extname='postgis' AND n.nspname='extensions') THEN
    RAISE EXCEPTION 'PostGIS must already exist in extensions schema';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_catalog.pg_roles WHERE rolname='service_role' AND rolbypassrls) THEN
    RAISE EXCEPTION 'Expected Supabase service_role with BYPASSRLS';
  END IF;
END
$guard$;

create table if not exists public.alert_rules (
    id bigint generated by default as identity primary key,
    region text not null,
    lawd_cd text,
    max_price_100m double precision not null,
    min_area double precision not null,
    event_type text not null,
    supply_type text default '전체',
    property_type text default '아파트',
    enabled boolean default true,
    created_at text not null
);

create table if not exists public.notifications (
    id bigint generated by default as identity primary key,
    event_key text unique,
    category text not null,
    title text not null,
    message text not null,
    is_read boolean default false,
    created_at text not null
);

create table if not exists public.source_snapshots (
    source text not null,
    item_key text not null,
    payload jsonb not null,
    first_seen_at text not null,
    last_seen_at text not null,
    primary key (source, item_key)
);

create table if not exists public.app_settings (
    key text primary key,
    value text not null
);


CREATE TABLE IF NOT EXISTS public.development_collection_runs (
  run_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  source_name text NOT NULL CHECK (btrim(source_name) <> ''),
  source_type text NOT NULL,
  source_url text,
  collector_version text NOT NULL,
  scope jsonb NOT NULL DEFAULT '{}'::jsonb CHECK (jsonb_typeof(scope)='object'),
  started_at timestamptz NOT NULL DEFAULT now(),
  finished_at timestamptz,
  status text NOT NULL DEFAULT 'RUNNING' CHECK (status IN ('RUNNING','SUCCEEDED','PARTIAL','FAILED','ABORTED')),
  dry_run boolean NOT NULL DEFAULT true,
  source_complete boolean NOT NULL DEFAULT false,
  new_count integer NOT NULL DEFAULT 0 CHECK (new_count>=0),
  changed_count integer NOT NULL DEFAULT 0 CHECK (changed_count>=0),
  unchanged_count integer NOT NULL DEFAULT 0 CHECK (unchanged_count>=0),
  validation_failed_count integer NOT NULL DEFAULT 0 CHECK (validation_failed_count>=0),
  missing_count integer NOT NULL DEFAULT 0 CHECK (missing_count>=0),
  errors jsonb NOT NULL DEFAULT '[]'::jsonb CHECK (jsonb_typeof(errors)='array'),
  CHECK (finished_at IS NULL OR finished_at>=started_at),
  CHECK ((status='RUNNING' AND finished_at IS NULL) OR (status<>'RUNNING' AND finished_at IS NOT NULL))
);

CREATE TABLE IF NOT EXISTS public.development_projects (
  project_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  project_type text NOT NULL CHECK (project_type IN (
    'MOATOWN','MOAHOUSE','REDEVELOPMENT','RECONSTRUCTION','SHINTONG',
    'MAINTENANCE_AREA','STATION_AREA','DISTRICT_UNIT_PLAN','PUBLIC_HOUSING',
    'URBAN_DEVELOPMENT','TRANSPORT','OTHER')),
  project_name text NOT NULL CHECK (btrim(project_name)<>''),
  official_authority text,
  external_id text,
  parent_project_id uuid REFERENCES public.development_projects(project_id) ON DELETE RESTRICT,
  related_types text[] NOT NULL DEFAULT '{}'::text[],
  sido text,
  sigungu text,
  dong text,
  legal_dong_code text,
  address text,
  status text NOT NULL DEFAULT 'UNKNOWN' CHECK (status IN ('ACTIVE','COMPLETED','CANCELLED','SUSPENDED','UNKNOWN')),
  validation_status text NOT NULL DEFAULT 'UNVERIFIED'
    CHECK (validation_status IN ('UNVERIFIED','VERIFIED','NEEDS_REVIEW','MISSING_FROM_SOURCE','REJECTED')),
  stage text,
  stage_raw text,
  stage_mapping_version text,
  selected_date date,
  notice_date date,
  area_m2 numeric CHECK (area_m2>0 AND area_m2<'Infinity'::numeric),
  planned_units integer CHECK (planned_units>=0),
  planned_floor integer CHECK (planned_floor>=0),
  planned_far numeric CHECK (planned_far>=0 AND planned_far<'Infinity'::numeric),
  location extensions.geography(Point,4326),
  geometry extensions.geometry(Geometry,4326),
  location_source text,
  location_verified_at timestamptz,
  geometry_source text,
  geometry_verified boolean NOT NULL DEFAULT false,
  geometry_verified_at timestamptz,
  canonical_source_id uuid,
  -- Constant discriminator columns enforce a VERIFIED official source via composite FK.
  canonical_source_official boolean NOT NULL DEFAULT true CHECK (canonical_source_official=true),
  canonical_source_validation text NOT NULL DEFAULT 'VERIFIED' CHECK (canonical_source_validation='VERIFIED'),
  confidence_level text NOT NULL DEFAULT 'UNKNOWN' CHECK (confidence_level IN ('HIGH','MEDIUM','LOW','UNKNOWN')),
  field_evidence jsonb NOT NULL DEFAULT '{}'::jsonb CHECK (jsonb_typeof(field_evidence)='object'),
  source_date date,
  last_verified_at timestamptz,
  revision bigint NOT NULL DEFAULT 1 CHECK (revision>0),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CHECK (parent_project_id IS NULL OR parent_project_id<>project_id),
  CHECK ((official_authority IS NULL AND external_id IS NULL) OR
         (official_authority IS NOT NULL AND btrim(official_authority)<>'' AND external_id IS NOT NULL AND btrim(external_id)<>'')),
  UNIQUE (official_authority, external_id),
  CHECK (location IS NULL OR (NOT extensions.ST_IsEmpty(location::extensions.geometry)
    AND location_source IS NOT NULL AND btrim(location_source)<>'')),
  CHECK (geometry IS NULL OR (
    extensions.GeometryType(geometry) IN ('POLYGON','MULTIPOLYGON')
    AND extensions.ST_NDims(geometry)=2
    AND NOT extensions.ST_IsEmpty(geometry) AND extensions.ST_IsValid(geometry)
    AND extensions.ST_XMin(extensions.Box3D(geometry))>=-180
    AND extensions.ST_XMax(extensions.Box3D(geometry))<=180
    AND extensions.ST_YMin(extensions.Box3D(geometry))>=-90
    AND extensions.ST_YMax(extensions.Box3D(geometry))<=90
    AND geometry_source IS NOT NULL AND btrim(geometry_source)<>'')),
  CHECK (NOT geometry_verified OR (geometry IS NOT NULL AND geometry_verified_at IS NOT NULL AND canonical_source_id IS NOT NULL)),
  CHECK ((status='UNKNOWN' AND stage IS NULL AND NOT geometry_verified AND validation_status<>'VERIFIED')
         OR (canonical_source_id IS NOT NULL AND last_verified_at IS NOT NULL)),
  CHECK (stage IS NULL OR (btrim(stage)<>'' AND stage_mapping_version IS NOT NULL)),
  CHECK (updated_at>=created_at)
);

CREATE TABLE IF NOT EXISTS public.development_project_sources (
  source_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  project_id uuid NOT NULL REFERENCES public.development_projects(project_id) ON DELETE RESTRICT,
  collection_run_id uuid REFERENCES public.development_collection_runs(run_id) ON DELETE RESTRICT,
  source_name text NOT NULL CHECK (btrim(source_name)<>''),
  source_type text NOT NULL CHECK (source_type IN ('OFFICIAL_API','OFFICIAL_NOTICE','OFFICIAL_WEBSITE','PUBLIC_INSTITUTION','SEARCH_RESULT','OTHER')),
  source_url text NOT NULL CHECK (source_url ~ '^https?://[^[:space:]]+$'),
  is_official boolean NOT NULL DEFAULT false,
  source_priority smallint GENERATED ALWAYS AS (CASE WHEN is_official THEN 100 ELSE 10 END) STORED,
  external_id text,
  document_title text,
  published_at timestamptz,
  effective_at timestamptz,
  collected_at timestamptz NOT NULL DEFAULT now(),
  verified_at timestamptz,
  verified_by text,
  validation_status text NOT NULL DEFAULT 'UNVERIFIED' CHECK (validation_status IN ('UNVERIFIED','VERIFIED','NEEDS_REVIEW','REJECTED')),
  raw_snapshot jsonb,
  content_hash text NOT NULL CHECK (content_hash ~ '^[0-9a-f]{64}$'),
  evidence jsonb NOT NULL DEFAULT '{}'::jsonb CHECK (jsonb_typeof(evidence)='object'),
  CHECK (NOT is_official OR source_type IN ('OFFICIAL_API','OFFICIAL_NOTICE','OFFICIAL_WEBSITE','PUBLIC_INSTITUTION')),
  CHECK (validation_status<>'VERIFIED' OR (verified_at IS NOT NULL AND verified_by IS NOT NULL AND btrim(verified_by)<>'')),
  UNIQUE (project_id, source_url, content_hash, is_official, validation_status),
  UNIQUE (source_id, project_id),
  UNIQUE (source_id, project_id, is_official, validation_status)
);

-- Add the circular reference only after both tables exist. Source row must belong to the same project.
DO $fk$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_catalog.pg_constraint
    WHERE conrelid='public.development_projects'::regclass AND conname='development_projects_canonical_source_fk') THEN
    ALTER TABLE public.development_projects ADD CONSTRAINT development_projects_canonical_source_fk
      FOREIGN KEY (canonical_source_id, project_id, canonical_source_official, canonical_source_validation)
      REFERENCES public.development_project_sources(source_id, project_id, is_official, validation_status)
      ON DELETE RESTRICT;
  END IF;
END
$fk$;

CREATE TABLE IF NOT EXISTS public.development_updates (
  update_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  project_id uuid NOT NULL REFERENCES public.development_projects(project_id) ON DELETE RESTRICT,
  source_id uuid NOT NULL,
  collection_run_id uuid REFERENCES public.development_collection_runs(run_id) ON DELETE RESTRICT,
  update_kind text NOT NULL CHECK (update_kind IN ('INITIAL','STATUS','STAGE','GEOMETRY','DETAIL','SOURCE_MISSING','REVERIFICATION')),
  previous_stage text,
  new_stage text,
  previous_status text CHECK (previous_status IN ('ACTIVE','COMPLETED','CANCELLED','SUSPENDED','UNKNOWN')),
  new_status text CHECK (new_status IN ('ACTIVE','COMPLETED','CANCELLED','SUSPENDED','UNKNOWN')),
  from_revision bigint CHECK (from_revision>0),
  to_revision bigint NOT NULL CHECK (to_revision>0),
  title text NOT NULL,
  description text,
  previous_snapshot jsonb,
  new_snapshot jsonb NOT NULL,
  changed_fields text[] NOT NULL DEFAULT '{}'::text[],
  published_at timestamptz,
  effective_at timestamptz,
  recorded_at timestamptz NOT NULL DEFAULT now(),
  verified_at timestamptz,
  event_hash text NOT NULL CHECK (event_hash ~ '^[0-9a-f]{64}$'),
  FOREIGN KEY (source_id, project_id) REFERENCES public.development_project_sources(source_id, project_id) ON DELETE RESTRICT,
  UNIQUE (project_id, to_revision),
  UNIQUE (project_id, event_hash),
  CHECK (from_revision IS NULL OR to_revision>from_revision),
  -- Missing from a listing is not a business status transition.
  CHECK (update_kind<>'SOURCE_MISSING' OR
    (new_status IS NOT DISTINCT FROM previous_status AND new_stage IS NOT DISTINCT FROM previous_stage))
);

CREATE TABLE IF NOT EXISTS public.geocode_cache (
  geocode_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  normalized_address text NOT NULL CHECK (btrim(normalized_address)<>''),
  address_hash text NOT NULL CHECK (address_hash ~ '^[0-9a-f]{64}$'),
  normalizer_version text NOT NULL,
  provider text NOT NULL,
  provider_version text NOT NULL DEFAULT 'v1',
  result_status text NOT NULL CHECK (result_status IN ('MATCHED','AMBIGUOUS','NOT_FOUND','ERROR')),
  location extensions.geography(Point,4326),
  matched_address text,
  legal_dong_code text,
  pnu text CHECK (pnu ~ '^[0-9]{19}$'),
  building_id text,
  accuracy text NOT NULL DEFAULT 'UNKNOWN' CHECK (accuracy IN ('BUILDING','PARCEL','ROAD','LOCALITY','UNKNOWN')),
  source_url text,
  raw_snapshot jsonb,
  content_hash text CHECK (content_hash ~ '^[0-9a-f]{64}$'),
  collected_at timestamptz NOT NULL DEFAULT now(),
  verified_at timestamptz,
  expires_at timestamptz NOT NULL,
  retry_after timestamptz,
  error_code text,
  UNIQUE (address_hash, normalizer_version, provider, provider_version),
  CHECK (expires_at>collected_at),
  CHECK (result_status<>'MATCHED' OR (location IS NOT NULL AND matched_address IS NOT NULL)),
  CHECK (result_status='MATCHED' OR location IS NULL),
  CHECK (location IS NULL OR NOT extensions.ST_IsEmpty(location::extensions.geometry))
);

CREATE INDEX IF NOT EXISTS alert_rules_enabled_region_idx ON public.alert_rules(enabled,region);
CREATE INDEX IF NOT EXISTS notifications_read_created_idx ON public.notifications(is_read,created_at DESC);
CREATE INDEX IF NOT EXISTS source_snapshots_seen_idx ON public.source_snapshots(last_seen_at);
CREATE INDEX IF NOT EXISTS development_runs_source_time_idx ON public.development_collection_runs(source_name,started_at DESC);
CREATE INDEX IF NOT EXISTS development_projects_region_idx ON public.development_projects(sido,sigungu,dong);
CREATE INDEX IF NOT EXISTS development_projects_type_status_idx ON public.development_projects(project_type,status,validation_status);
CREATE INDEX IF NOT EXISTS development_projects_parent_idx ON public.development_projects(parent_project_id);
CREATE INDEX IF NOT EXISTS development_projects_canonical_idx ON public.development_projects(canonical_source_id);
CREATE INDEX IF NOT EXISTS development_projects_location_gist ON public.development_projects USING gist(location);
CREATE INDEX IF NOT EXISTS development_projects_geometry_gist ON public.development_projects USING gist(geometry);
CREATE INDEX IF NOT EXISTS development_projects_geometry_geog_gist ON public.development_projects USING gist((geometry::extensions.geography));
CREATE INDEX IF NOT EXISTS development_sources_project_time_idx ON public.development_project_sources(project_id,published_at DESC);
CREATE INDEX IF NOT EXISTS development_sources_run_idx ON public.development_project_sources(collection_run_id);
CREATE INDEX IF NOT EXISTS development_updates_project_time_idx ON public.development_updates(project_id,recorded_at DESC);
CREATE INDEX IF NOT EXISTS development_updates_source_idx ON public.development_updates(source_id,project_id);
CREATE INDEX IF NOT EXISTS development_updates_run_idx ON public.development_updates(collection_run_id);
CREATE INDEX IF NOT EXISTS geocode_cache_expiry_idx ON public.geocode_cache(expires_at);
CREATE INDEX IF NOT EXISTS geocode_cache_location_gist ON public.geocode_cache USING gist(location);

-- No anonymous/browser access, no global/default privilege changes, no RLS bypass policies.
GRANT USAGE ON SCHEMA public, extensions TO service_role;
ALTER TABLE public.alert_rules ENABLE ROW LEVEL SECURITY;
REVOKE ALL PRIVILEGES ON TABLE public.alert_rules FROM PUBLIC, anon, authenticated, service_role;
ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;
REVOKE ALL PRIVILEGES ON TABLE public.notifications FROM PUBLIC, anon, authenticated, service_role;
ALTER TABLE public.source_snapshots ENABLE ROW LEVEL SECURITY;
REVOKE ALL PRIVILEGES ON TABLE public.source_snapshots FROM PUBLIC, anon, authenticated, service_role;
ALTER TABLE public.app_settings ENABLE ROW LEVEL SECURITY;
REVOKE ALL PRIVILEGES ON TABLE public.app_settings FROM PUBLIC, anon, authenticated, service_role;
ALTER TABLE public.development_collection_runs ENABLE ROW LEVEL SECURITY;
REVOKE ALL PRIVILEGES ON TABLE public.development_collection_runs FROM PUBLIC, anon, authenticated, service_role;
ALTER TABLE public.development_projects ENABLE ROW LEVEL SECURITY;
REVOKE ALL PRIVILEGES ON TABLE public.development_projects FROM PUBLIC, anon, authenticated, service_role;
ALTER TABLE public.development_project_sources ENABLE ROW LEVEL SECURITY;
REVOKE ALL PRIVILEGES ON TABLE public.development_project_sources FROM PUBLIC, anon, authenticated, service_role;
ALTER TABLE public.development_updates ENABLE ROW LEVEL SECURITY;
REVOKE ALL PRIVILEGES ON TABLE public.development_updates FROM PUBLIC, anon, authenticated, service_role;
ALTER TABLE public.geocode_cache ENABLE ROW LEVEL SECURITY;
REVOKE ALL PRIVILEGES ON TABLE public.geocode_cache FROM PUBLIC, anon, authenticated, service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.alert_rules TO service_role;
GRANT SELECT, INSERT, UPDATE ON TABLE public.notifications, public.source_snapshots, public.app_settings TO service_role;
GRANT SELECT, INSERT, UPDATE ON TABLE public.development_projects, public.development_collection_runs, public.geocode_cache TO service_role;
-- Sources and accepted history are append-only through the application's REST role.
GRANT SELECT, INSERT ON TABLE public.development_project_sources, public.development_updates TO service_role;
REVOKE ALL PRIVILEGES ON SEQUENCE public.alert_rules_id_seq, public.notifications_id_seq FROM PUBLIC, anon, authenticated, service_role;
GRANT USAGE, SELECT ON SEQUENCE public.alert_rules_id_seq, public.notifications_id_seq TO service_role;

COMMENT ON COLUMN public.development_projects.geometry IS 'EPSG:4326 actual boundary; Polygon or MultiPolygon only. Never construct a business boundary from a representative point.';
COMMENT ON COLUMN public.development_projects.validation_status IS 'Data quality independent of business status. Missing source records require review, never automatic cancellation.';
COMMENT ON COLUMN public.development_projects.canonical_source_id IS 'Verified official evidence; SEARCH_RESULT cannot be canonical. Collector must also check field evidence, priority, effective date and hash.';
COMMENT ON TABLE public.development_updates IS 'Append-only application history. Collector must write master revision and history in the same DB transaction; REST multi-request atomicity is not provided by this schema.';
COMMENT ON TABLE public.development_collection_runs IS 'Counters describe observed candidates in dry-run; dry-run collectors must not apply changes. Errors must not contain credentials.';
NOTIFY pgrst, 'reload schema';
COMMIT;
